#pragma once

#include "stdint.h"


enum ret_code_e
{
  RET_CODE_OK   = 0,
  RET_CODE_EOF,
  RET_CODE_EOL,
  RET_CODE_PARSING_INPUT_ERROR,
  RET_CODE_NO_MEMORY,
  RET_CODE_UNINITIALIZED,
  RET_CODE_INTERNAL_ERROR_001,
  RET_CODE_INTERNAL_ERROR_002,
  RET_CODE_INTERNAL_ERROR_003,
  RET_CODE_INTERNAL_ERROR_004,
  RET_CODE_INTERNAL_ERROR_005,
  RET_CODE_INTERNAL_ERROR_006,
  RET_CODE_INTERNAL_ERROR_007,
  RET_CODE_INTERNAL_ERROR_008,
  RET_CODE_INTERNAL_ERROR_009,
  RET_CODE_INTERNAL_ERROR_010,

  RET_CODES
};

typedef int32_t ret_code_t;

